### ISSUE TITLE
Any demos?

### ISSUE THREAD

**Issue by jhnferraris** [fjtrujy/react-native-flipboard-flex#1]
Hello,

Does this have a demo gif/vid somewhere?

Thanks!

**Comment by fjtrujy** [comment]
Hello, 
Thanks for your suggestion.
I will try to update the readme today

**Comment by fjtrujy** [comment]
So I have updated the readme with how to use it.
I didn't put any GIF, because and the end this is just a proxy to the original native project. Flipboard-flex, but on the other hand I have linked this here, so clicking on the readme you will be redirected to the native project, where you have the GIFs.

Thanks
